# Generated by Django 5.1.7 on 2025-04-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviveride_spa', '0002_notification_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=1000000),
        ),
    ]
